name: Publish Docker Branch
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Get Branch
        run: echo ::set-env name=BRANCH::${GITHUB_REF#refs/heads/}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VERSION: ${{ github.sha }}
        with:
          name: tautulli/tautulli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildargs: VERSION, BRANCH
