name: Publish Docker Release
on:
  release:
    types: [published, prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Get Branch
        run: echo ::set-env name=BRANCH::${GITHUB_REF#refs/heads/}
      - name: Get Release Version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          VERSION: ${{ github.sha }}
        with:
          name: tautulli/tautulli
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          buildargs: VERSION, BRANCH
          tags: ${{ env.RELEASE_VERSION }}
      - name: Post Status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          job: ${{ github.workflow }}
          nofail: true
