name: Publish Docker Release
on:
  release:
    types: [published, prereleased]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        VERSION: ${{ github.sha }}
      with:
        name: wreave/tautulli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        buildargs: VERSION
        tags: ${{ env.RELEASE_VERSION }}
